#
###################################
# Site wide configuration
####################################
#
title: Soham Bhattacharyya
email: soham@dal.com
description: Notes, pointers and cheatsheets.
url: "https://sohambhattacharyya.github.io"
#baseurl: "/"
keywords: ["DSP", "MATLAB", "Deep Learning", "Electronics", "Communications", "Engineering", "Statistics", "Machine Learning", "Neural Network", "Artificial Intelligence", "Eagle", "Arduino", "Raspberry Pi", "Diptrace", "Proteus", "Simulink", "FPGA"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          India/Kolkata
markdown:          kramdown
mathjax:           true
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /blog/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Soham Bhattacharyya
  avatar: profile.jpg
  job: "MASc, ECE"
  bio: "Notes, pointers and cheatsheets."
  email: soham@dal.ca
  disqus-shortname: sohambhattacharyya
  twitter: __Soham #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-83935417-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: SohamBhattacharyya #username
  stackoverflow: 3956752/soham-bhattacharyya # 123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: soham-bhattacharyya #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud:
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username

plugins:
  - jekyll-seo-tag

# Exclude list
exclude: [README.md, Gemfile.lock, node_modules, gulpfile.js, Rakefile]
